/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hhn.qlqa027a.GUI;

import hhn.qlqa027a.entities.Employee;
import hhn.qlqa027a.entities.Role;
import hhn.qlqa027a.entities.Status;
import hhn.qlqa027a.framework.AbstractDataPageView;
import hhn.qlqa027a.framework.EntityTableColumn;
import hhn.qlqa027a.util.I18n;
import hhn.qlqa027a.util.ViewHelpers;
import java.awt.BorderLayout;

/**
 *
 * @author Huy
 */
public class EmployeePage extends AbstractDataPageView<Employee>{
   
    /**
     * Creates new form testPage1
     */
    public EmployeePage() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void addTableColumns() {
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Employee.Page.FullName"), "fullName", String.class, 300));

        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Employee.Page.Phone"), "phone", String.class, 200));
        
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Employee.Page.Email"), "email", String.class, 200));
        
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Employee.Page.Role"), "role", Role.class, 200));
        
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Employee.Page.Status"), "status", Status.class, 200));
    }
        
    @Override
    public String getIconPath() {
        return ViewHelpers.ICONS16 + "customer.png";
    }
   
    @Override
    public String getTitle() {
        return I18n.CUSTOMERS.getString("Employee.Page.Title");
    }

    private void setLayout(BorderLayout borderLayout) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    // End of variables declaration//GEN-END:variables
}
