/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hhn.qlqa027a.GUI;

import hhn.qlqa027a.entities.Employeeschedule;
import hhn.qlqa027a.framework.AbstractDataPageView;
import hhn.qlqa027a.framework.EntityTableColumn;
import hhn.qlqa027a.util.I18n;
import hhn.qlqa027a.util.ViewHelpers;
import java.awt.BorderLayout;

/**
 *
 * @author Huy
 */
public class EmployeeSchedulePage extends AbstractDataPageView<Employeeschedule>{
   
    /**
     * Creates new form testPage1
     */
    public EmployeeSchedulePage() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void addTableColumns() {
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Employeeschedule.Page.EmployeeName"), "employee", String.class, 300));
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Employeeschedule.Page.Schedule"), "schedule", String.class, 300));
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Employeeschedule.Page.Status"), "status", String.class, 300));
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Employeeschedule.Page.MinutesLate"), "minutesLate", String.class, 300));       
    }
        
    @Override
    public String getIconPath() {
        return ViewHelpers.ICONS16 + "role.png";
    }
   
    @Override
    public String getTitle() {
        return I18n.CUSTOMERS.getString("Employeeschedule.Page.Title");
    }

    private void setLayout(BorderLayout borderLayout) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
