/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hhn.qlqa027a.GUI;

import hhn.qlqa027a.entities.Category;
import hhn.qlqa027a.entities.Food;
import hhn.qlqa027a.entities.Status;
import hhn.qlqa027a.framework.AbstractDataPageView;
import hhn.qlqa027a.framework.EntityTableColumn;
import hhn.qlqa027a.util.I18n;
import hhn.qlqa027a.util.ViewHelpers;
import java.awt.BorderLayout;

/**
 *
 * @author Administrator
 */
public class FoodPage extends AbstractDataPageView<Food>{
    
    public FoodPage() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>                        

    @Override
    public void addTableColumns() {
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Food.Page.Name"), "name", String.class, 300));

        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Food.Page.Price"), "price", Double.class, 300));  
        
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Food.Page.Category"), "category", Category.class, 300)); 
        
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Food.Page.Status"), "status", Status.class, 200));
    }
        
    @Override
    public String getIconPath() {
        return ViewHelpers.ICONS16 + "food.png";
    }
   
    @Override
    public String getTitle() {
        return I18n.CUSTOMERS.getString("Food.Page.Title");
    }

    private void setLayout(BorderLayout borderLayout) {
        
    }

    // Variables declaration - do not modify                     
    private com.toedter.calendar.JDateChooser jDateChooser1;
    // End of variables declaration  
}
