/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hhn.qlqa027a.GUI;

import hhn.qlqa027a.entities.Shift;
import hhn.qlqa027a.framework.AbstractDataPageView;
import hhn.qlqa027a.framework.EntityTableColumn;
import hhn.qlqa027a.util.I18n;
import hhn.qlqa027a.util.ViewHelpers;
import java.awt.BorderLayout;

/**
 *
 * @author Huy
 */
public class ShiftPage extends AbstractDataPageView<Shift>{
   
    /**
     * Creates new form testPage1
     */
    public ShiftPage() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void addTableColumns() {
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Shift.Page.Name"), "name", String.class, 300));
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Shift.Page.Salary"), "salary", String.class, 200));
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Shift.Page.MinServicers"), "minServicers", String.class, 300));

        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Shift.Page.MaxServicers"), "maxServicers", String.class, 200));
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Shift.Page.MinBartenders"), "minBartenders", String.class, 300));

        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Shift.Page.MaxBartenders"), "maxBartenders", String.class, 200));
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Shift.Page.MinManagers"), "minManagers", String.class, 200));
        getTableModel().addColumn(new EntityTableColumn(
                I18n.CUSTOMERS.getString("Shift.Page.MaxManagers"), "maxManagers", String.class, 300));

    }
        
    @Override
    public String getIconPath() {
        return ViewHelpers.ICONS16 + "customer.png";
    }
   
    @Override
    public String getTitle() {
        return I18n.CUSTOMERS.getString("Shift.Page.Title");
    }

    private void setLayout(BorderLayout borderLayout) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    // End of variables declaration//GEN-END:variables
}
